In [ ]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [ ]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv('lending_data.csv')

# Review the DataFrame

df.sample(5)

loan_size  interest_rate  borrower_income  debt_to_income  \
6690      8600.0          6.800            44600        0.327354   
9041     10500.0          7.602            52100        0.424184   
29671     9300.0          7.088            47300        0.365751   
33096    10400.0          7.553            51700        0.419729   
15296    10400.0          7.558            51700        0.419729   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
6690                 3                 0       14600            0  
9041                 4                 1       22100            0  
29671                3                 0       17300            0  
33096                4                 1       21700            0  
15296                4                 1       21700            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [ ]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df['loan_status']

# Separate the X variable, the features
X = df.drop('loan_status', axis=1)


In [ ]:
# Review the y variable Series
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64


In [ ]:
# Review the X variable DataFrame

X


loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 7 columns]

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [ ]:
# Check the balance of our target values

target_balance = y.value_counts()
print(target_balance)


0    75036
1     2500
Name: loan_status, dtype: int64


### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [ ]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [ ]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model

logreg = LogisticRegression(random_state=1)

# Fit the model using training data

logreg.fit(X_train, y_train)


LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [ ]:
# Make a prediction using the testing data
y_pred = logreg.predict(X_test)

# Print the predictions
print(y_pred)


[0 0 0 ... 0 0 0]


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [ ]:
# Print the balanced_accuracy score of the model
from sklearn.metrics import balanced_accuracy_score

# Calculate the balanced accuracy score
balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
print("Balanced Accuracy Score:", balanced_accuracy)


Balanced Accuracy Score: 0.9521352751368186


In [ ]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
confusion_mtx = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mtx)

Confusion Matrix:
[[14926    75]
 [   46   461]]


In [ ]:
# Print the classification report for the model
# YOUR CODE HERE!

from sklearn.metrics import classification_report

# Print the classification report
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_rep)


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15001
           1       0.86      0.91      0.88       507

    accuracy                           0.99     15508
   macro avg       0.93      0.95      0.94     15508
weighted avg       0.99      0.99      0.99     15508



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** WRITE YOUR ANSWER HERE!
To assess how well the logistic regression model predicts both the "0" (healthy loan) and "1" (high-risk loan) labels based on the available data, we can examine the relevant metrics from the classification report and confusion matrix. Specifically, we can focus on precision, recall, and F1-score for each class.

In the classification report, the metrics for the "0" class indicate how well the model predicts healthy loans, while the metrics for the "1" class indicate the model's performance in predicting high-risk loans. Precision measures the proportion of correctly predicted instances of a specific class out of all instances predicted as that class. Recall, also known as sensitivity or true positive rate, measures the proportion of correctly predicted instances of a class out of all actual instances of that class. F1-score is the harmonic mean of precision and recall, providing a balanced measure of both metrics.

To interpret the model's performance for each class, look at the classification report and compare the precision, recall, and F1-score for the "0" and "1" classes. A higher value indicates better performance. Additionally, examine the confusion matrix to see the number of true positives, true negatives, false positives, and false negatives for each class.

By considering these metrics, you can gain insights into how well the logistic regression model predicts both healthy loans (class "0") and high-risk loans (class "1") based on the provided data.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points.

In [ ]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
random_oversampler = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_train_resampled, y_train_resampled = random_oversampler.fit_resample(X_train, y_train)


In [ ]:
# Count the distinct values of the resampled labels data
label_counts_resampled = y_train_resampled.value_counts()
print(label_counts_resampled)


0    60035
1    60035
Name: loan_status, dtype: int64


### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [ ]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logreg_resampled = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
logreg_resampled.fit(X_train_resampled, y_train_resampled)

# Make a prediction using the testing data
y_pred_resampled = logreg_resampled.predict(X_test)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [ ]:
# Print the balanced_accuracy score of the model
# YOUR CODE HERE!
from sklearn.metrics import balanced_accuracy_score

# Calculate the balanced accuracy score
balanced_accuracy_resampled = balanced_accuracy_score(y_test, y_pred_resampled)
print("Balanced Accuracy Score:", balanced_accuracy_resampled)


Balanced Accuracy Score: 0.9941749445500477


In [ ]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!

from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
confusion_mtx_resampled = confusion_matrix(y_test, y_pred_resampled)
print("Confusion Matrix:")
print(confusion_mtx_resampled)


Confusion Matrix:
[[14915    86]
 [    3   504]]


In [ ]:
# Print the classification report for the model
# YOUR CODE HERE!

from sklearn.metrics import classification_report

# Print the classification report
classification_rep_resampled = classification_report(y_test, y_pred_resampled)
print("Classification Report:")
print(classification_rep_resampled)


Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.85      0.99      0.92       507

    accuracy                           0.99     15508
   macro avg       0.93      0.99      0.96     15508
weighted avg       1.00      0.99      0.99     15508



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** YOUR ANSWER HERE!

To assess how well the logistic regression model, fitted with oversampled data, predicts both the "0" (healthy loan) and "1" (high-risk loan) labels based on the availabe data, we can examine the relevant metrics from the classification report and confusion matrix. Specifically, focus on precision, recall, and F1-score for each class.

In the classification report, the metrics for the "0" class indicate how well the model predicts healthy loans, while the metrics for the "1" class indicate the model's performance in predicting high-risk loans. Precision measures the proportion of correctly predicted instances of a specific class out of all instances predicted as that class. Recall, also known as sensitivity or true positive rate, measures the proportion of correctly predicted instances of a class out of all actual instances of that class. F1-score is the harmonic mean of precision and recall, providing a balanced measure of both metrics.

To interpret the model's performance for each class, we should look at the classification report and compare the precision, recall, and F1-score for the "0" and "1" classes. A higher value indicates better performance. Additionally, examine the confusion matrix to see the number of true positives, true negatives, false positives, and false negatives for each class.

By considering these metrics, you can gain insights into how well the logistic regression model, fit with oversampled data, predicts both healthy loans (class "0") and high-risk loans (class "1") based on the provided data.